import '../styles/global.css'
import { Navation } from './components/Navigation'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <head>
        <title>First Next 13</title>
      </head>
      <body>
        <Navation />
        {children}
      </body>
    </html>
  )
}
